version: "3.0"

services: 
    backend:
        image: devansh42/shree-backend:latest
        expose: 
            - 4200
        ports: 
            - "4200:4200" 
        depends_on: 
            - redis
            - ca    
        networks: 
            - ca
            - backend   
        volumes: 
            - "/dvol/shree/backend:/root"    
        command: "./back -baddr :4200 -caddr ca:5200 -raddr shree_redis_1:6379"    
  
  
  
    redis:
        image: redis:alpine
        expose: 
            - 6379
        networks: 
            - ca
        volumes: 
            - "/dvol/shree/redis:/data"    
            
    ca:
        image:  devansh42/shree-ca:latest
        networks: 
            - ca
        expose:
            - 5200    
        volumes: 
            - "/dvols/shree/ca:/root"
            - "/dvols/shree/keys/ca:/ca/keys"    
        command: "./ca -addr :5200 -hprv /ca/keys/ca_host_key -hpub /ca/keys/ca_host_key.pub -uprv /ca/keys/ca_user_key -upub /ca/keys/ca_user_key.pub"   
        
        

    serv:
        image: devansh42/shree-serv:latest                
        networks: 
            - backend
        depends_on: 
            - backend
        expose:
            - 6200
        volumes: 
            - "/dvols/shree/serv:/root"
            - "/dvols/shree/keys/serv:/serv/keys"    
        command: "./serv -addr :6200 -baddr :4200 -host localhost -prv /serv/keys/id_host -pub /serv/keys/id_host.pub"        


networks: 
    ca:
        driver: bridge
     
    backend:
        driver: bridge
     